on:  
  workflow_dispatch:

jobs:
  if-Windows-else:
    runs-on: self-hosted
    steps:
      - name: condition 1
        if: runner.os == 'Windows'
        run: |
          $label = Get-Content $env:GITHUB_EVENT_PATH | ConvertFrom-Json | Select *
          Write-Host "$label"
          Write-Host "$env:GITHUB_EVENT_NAME"
          Write-Host "$env:GITHUB_HEAD_REF"
          pwd
          flyway check -code -changes -dryrun -configFiles="C:\Users\spachipala\actions-runner\_work\fw_poc\fw_poc\flyway.toml,C:\Users\spachipala\actions-runner\_work\fw_poc\fw_poc\flyway.user.toml" -workingDirectory="C:\Users\spachipala\actions-runner\_work\fw_poc\fw_poc" -environment=Dev
          
      - name: condition 2
        if: runner.os != 'Windows'
        run: echo "The operating system on the runner is not Windows, it's $RUNNER_OS."
